server:
  port: 8082
grpc:
  server:
   port: 8888
spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
##        instance-id: ${spring.application.name}-${random.value}
        port: ${grpc.server.port}
        register-health-check: false




