// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package cn.sp.lib;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
